import type { DB } from './types';
import { hash, avatarFor } from './utils';

const now = Date.now();
const d = (days: number) => now - days * 86400000;

export function buildSeed(): DB {
  return {
    users: [
      { id: 'u-ava', name: 'Ava Sinclair', email: 'freelancer@demo.io', passwordHash: hash('demo123'), role: 'freelancer', avatar: avatarFor('Ava Sinclair'), createdAt: d(220) },
      { id: 'u-kai', name: 'Kai Nakamura', email: 'kai@fh.io', passwordHash: hash('demo123'), role: 'freelancer', avatar: avatarFor('Kai Nakamura'), createdAt: d(400) },
      { id: 'u-zoe', name: 'Zoe Mensah', email: 'zoe@fh.io', passwordHash: hash('demo123'), role: 'freelancer', avatar: avatarFor('Zoe Mensah'), createdAt: d(310) },
      { id: 'u-leo', name: 'Leo Fernandez', email: 'leo@fh.io', passwordHash: hash('demo123'), role: 'freelancer', avatar: avatarFor('Leo Fernandez'), createdAt: d(150) },
      { id: 'u-ira', name: 'Ira Volkov', email: 'ira@fh.io', passwordHash: hash('demo123'), role: 'freelancer', avatar: avatarFor('Ira Volkov'), createdAt: d(90) },
      { id: 'u-marcus', name: 'Marcus Reed', email: 'client@demo.io', passwordHash: hash('demo123'), role: 'client', avatar: avatarFor('Marcus Reed'), company: 'Nova Labs', createdAt: d(500) },
      { id: 'u-priya', name: 'Priya Anand', email: 'priya@fh.io', passwordHash: hash('demo123'), role: 'client', avatar: avatarFor('Priya Anand'), company: 'Bloom Commerce', createdAt: d(280) },
    ],
    profiles: [
      {
        userId: 'u-ava', title: 'Senior Frontend Engineer & UI Designer', location: 'Lisbon, Portugal',
        bio: 'I craft fast, elegant web products. 7+ years shipping React apps for startups and scale-ups, with a designer\u2019s eye for motion and detail.',
        skills: ['React', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Next.js', 'Figma', 'Node.js'],
        hourlyRate: 68, availability: 'Available · 30 hrs/week',
        github: 'github.com/avasinclair', linkedin: 'linkedin.com/in/avasinclair', website: 'ava.design',
        resumeSummary: 'Frontend specialist focused on design systems, performance and accessible interfaces. Led UI for 3 funded startups; shipped products used by 2M+ people.',
        education: [
          { school: 'University of Porto', degree: 'BSc Computer Science', years: '2013 – 2016' },
          { school: 'Interaction Design Foundation', degree: 'UX Certification', years: '2018' },
        ],
        experience: [
          { company: 'Fable (YC W21)', role: 'Lead Frontend Engineer', years: '2021 – 2024', description: 'Built the design system and core editor experience; grew team from 2 to 8 engineers.' },
          { company: 'Freelance', role: 'Product Engineer', years: '2018 – 2021', description: 'Delivered 25+ client projects: dashboards, marketing sites, mobile-first web apps.' },
        ],
        certifications: ['AWS Certified Developer – Associate', 'Google UX Design Certificate'],
        portfolio: [
          { title: 'Pulse Analytics Dashboard', image: 'https://picsum.photos/seed/fh-p1/640/400', description: 'Realtime analytics suite with 40+ chart components.', link: 'ava.design/pulse' },
          { title: 'Orbit Banking App', image: 'https://picsum.photos/seed/fh-p2/640/400', description: 'Mobile-first neobank UI — onboarding, cards, transfers.', link: 'ava.design/orbit' },
          { title: 'Terra Marketing Site', image: 'https://picsum.photos/seed/fh-p3/640/400', description: 'Award-nominated WebGL landing experience.' },
        ],
        completedProjects: [
          { title: 'SaaS billing portal for Finch', description: 'Stripe integration, usage metering UI.', year: '2024' },
          { title: 'Design system for Habitat', description: '120-component library in React + Storybook.', year: '2023' },
        ],
        reviews: [
          { id: 'r1', clientId: 'u-priya', clientName: 'Priya Anand', rating: 5, text: 'Ava is world-class. Pixel-perfect delivery, ahead of schedule.', createdAt: d(60) },
          { id: 'r2', clientId: 'u-marcus', clientName: 'Marcus Reed', rating: 5, text: 'Exceptional communication and craft. Hiring again.', createdAt: d(120) },
        ],
      },
      {
        userId: 'u-kai', title: 'Full-Stack Developer (Node & Go)', location: 'Osaka, Japan',
        bio: 'Backend-leaning full-stack engineer. APIs, queues, infra — I make systems boring and reliable.',
        skills: ['Node.js', 'Go', 'PostgreSQL', 'MongoDB', 'Docker', 'AWS', 'React'],
        hourlyRate: 75, availability: 'Available · 20 hrs/week',
        github: 'github.com/kainak', linkedin: 'linkedin.com/in/kainak', website: 'kai.dev',
        resumeSummary: '9 years building distributed systems. Ex-Rakuten. Comfortable owning products end to end.',
        education: [{ school: 'Osaka University', degree: 'MSc Software Engineering', years: '2012 – 2014' }],
        experience: [{ company: 'Rakuten', role: 'Senior Backend Engineer', years: '2014 – 2020', description: 'Payments platform serving 100M+ users.' }],
        certifications: ['CKA – Certified Kubernetes Administrator'],
        portfolio: [
          { title: 'Ledger API Platform', image: 'https://picsum.photos/seed/fh-k1/640/400', description: 'Double-entry ledger with 5k rps throughput.' },
          { title: 'Fleet IoT Ingest', image: 'https://picsum.photos/seed/fh-k2/640/400', description: 'Telemetry pipeline on Kafka + Go.' },
        ],
        completedProjects: [{ title: 'Marketplace escrow service', description: 'Go microservice, Stripe Connect.', year: '2024' }],
        reviews: [{ id: 'r3', clientId: 'u-marcus', clientName: 'Marcus Reed', rating: 4.5, text: 'Rock-solid backend work.', createdAt: d(90) }],
      },
      {
        userId: 'u-zoe', title: 'Product Designer — Brand & UI/UX', location: 'Accra, Ghana',
        bio: 'Designer of joyful, human interfaces. Strategy → wireframes → polished UI → dev handoff.',
        skills: ['Figma', 'UI/UX', 'Brand Design', 'Prototyping', 'Design Systems', 'Webflow'],
        hourlyRate: 55, availability: 'Available now · full-time',
        github: '', linkedin: 'linkedin.com/in/zoemensah', website: 'zoe.studio',
        resumeSummary: '6 years in product design across fintech and health. I turn fuzzy ideas into shippable specs.',
        education: [{ school: 'Ashesi University', degree: 'BA Design & Technology', years: '2014 – 2018' }],
        experience: [{ company: 'Chipper Cash', role: 'Product Designer', years: '2019 – 2023', description: 'Owned send-money and KYC flows for 5M users.' }],
        certifications: ['NN/g UX Certificate'],
        portfolio: [
          { title: 'Halo Health App', image: 'https://picsum.photos/seed/fh-z1/640/400', description: 'Telemedicine app — 4.8★ on both stores.' },
          { title: 'Sable Brand System', image: 'https://picsum.photos/seed/fh-z2/640/400', description: 'Full rebrand + design language.' },
        ],
        completedProjects: [{ title: 'Onboarding redesign for Lend', description: '+34% activation.', year: '2024' }],
        reviews: [{ id: 'r4', clientId: 'u-priya', clientName: 'Priya Anand', rating: 5, text: 'Zoe\u2019s designs converted beautifully.', createdAt: d(45) }],
      },
      {
        userId: 'u-leo', title: 'Mobile Engineer — React Native & Swift', location: 'Buenos Aires, Argentina',
        bio: 'I ship native-quality mobile apps fast. 40+ App Store releases.',
        skills: ['React Native', 'Swift', 'Kotlin', 'Expo', 'Firebase', 'GraphQL'],
        hourlyRate: 60, availability: 'Available · 40 hrs/week',
        github: 'github.com/leofdz', linkedin: 'linkedin.com/in/leofdz', website: '',
        resumeSummary: 'Mobile-first engineer, ex-MercadoLibre. Performance-obsessed.',
        education: [{ school: 'UBA', degree: 'Ingeniería en Informática', years: '2013 – 2018' }],
        experience: [{ company: 'MercadoLibre', role: 'Mobile Engineer', years: '2018 – 2022', description: 'Checkout squad, LATAM\u2019s largest marketplace.' }],
        certifications: [],
        portfolio: [{ title: 'Trak Fitness', image: 'https://picsum.photos/seed/fh-l1/640/400', description: '500k downloads, RN + HealthKit.' }],
        completedProjects: [{ title: 'Delivery driver app', description: 'Offline-first RN app.', year: '2023' }],
        reviews: [],
      },
      {
        userId: 'u-ira', title: 'ML Engineer — LLMs & Computer Vision', location: 'Tbilisi, Georgia',
        bio: 'From notebooks to production: RAG systems, fine-tuning, CV pipelines.',
        skills: ['Python', 'PyTorch', 'LangChain', 'RAG', 'Computer Vision', 'FastAPI', 'MLOps'],
        hourlyRate: 90, availability: 'Limited · 15 hrs/week',
        github: 'github.com/iravolkov', linkedin: 'linkedin.com/in/iravolkov', website: 'ira.ml',
        resumeSummary: 'PhD-trained ML engineer. I deliver measurable model improvements, not demos.',
        education: [{ school: 'ITMO University', degree: 'PhD Machine Learning', years: '2015 – 2019' }],
        experience: [{ company: 'Wander AI', role: 'Staff ML Engineer', years: '2020 – 2024', description: 'Built retrieval stack powering 1M queries/day.' }],
        certifications: ['TensorFlow Developer Certificate'],
        portfolio: [{ title: 'DocuMind RAG', image: 'https://picsum.photos/seed/fh-i1/640/400', description: 'Enterprise document QA, 92% answer accuracy.' }],
        completedProjects: [{ title: 'Defect detection CV model', description: '99.1% precision on factory line.', year: '2024' }],
        reviews: [{ id: 'r5', clientId: 'u-marcus', clientName: 'Marcus Reed', rating: 5, text: 'Ira delivered beyond scope. Brilliant.', createdAt: d(30) }],
      },
    ],
    projects: [
      {
        id: 'p-dash', clientId: 'u-marcus', title: 'Analytics dashboard for SaaS platform',
        description: 'We need a beautiful, fast analytics dashboard for our B2B SaaS. Charts (line, bar, funnel, cohort), date-range filtering, CSV export, and a clean dark theme. Design references will be provided. Backend REST API is ready — this is a frontend-focused engagement with tight collaboration with our backend team.\n\nDeliverables: responsive React app, component library, docs, and handoff session.',
        skills: ['React', 'TypeScript', 'Tailwind CSS', 'Charts'], budget: 4500, category: 'Web Development',
        deadline: new Date(now + 30 * 86400000).toISOString().slice(0, 10), experienceLevel: 'Expert', type: 'fixed',
        freelancersRequired: 1, attachments: ['brand-guide.pdf', 'api-spec.yaml'], status: 'open', selectedFreelancerIds: [], createdAt: d(3),
      },
      {
        id: 'p-mobile', clientId: 'u-marcus', title: 'React Native app for field technicians',
        description: 'Offline-first mobile app for 200 field techs: job lists, photo capture, signatures, sync queue. Expo preferred. You\u2019ll work with our PM and one backend dev. 8–10 week engagement.',
        skills: ['React Native', 'Expo', 'Offline Sync', 'TypeScript'], budget: 55, category: 'Mobile Development',
        deadline: new Date(now + 60 * 86400000).toISOString().slice(0, 10), experienceLevel: 'Intermediate', type: 'hourly',
        freelancersRequired: 1, attachments: ['wireframes.fig'], status: 'open', selectedFreelancerIds: [], createdAt: d(6),
      },
      {
        id: 'p-brand', clientId: 'u-priya', title: 'Complete brand identity + landing page',
        description: 'Bloom Commerce is rebranding. We need logo, color system, typography, brand guidelines, and a stunning landing page (Webflow or code). We love brands like Linear, Arc, and Ghia — confident, minimal, warm.',
        skills: ['Brand Design', 'Figma', 'Webflow', 'UI/UX'], budget: 6000, category: 'UI/UX Design',
        deadline: new Date(now + 40 * 86400000).toISOString().slice(0, 10), experienceLevel: 'Expert', type: 'fixed',
        freelancersRequired: 1, attachments: [], status: 'open', selectedFreelancerIds: [], createdAt: d(2),
      },
      {
        id: 'p-rag', clientId: 'u-priya', title: 'RAG chatbot over product documentation',
        description: 'Build a retrieval-augmented chatbot over ~2,000 pages of product docs. Must cite sources, handle follow-ups, and hit <2s latency. Stack open to your recommendation (we lean LangChain + pgvector). Includes eval harness.',
        skills: ['Python', 'LangChain', 'RAG', 'FastAPI'], budget: 8000, category: 'AI & Machine Learning',
        deadline: new Date(now + 45 * 86400000).toISOString().slice(0, 10), experienceLevel: 'Expert', type: 'fixed',
        freelancersRequired: 1, attachments: ['docs-sample.zip'], status: 'open', selectedFreelancerIds: [], createdAt: d(1),
      },
      {
        id: 'p-api', clientId: 'u-marcus', title: 'Payments API integration (Stripe Connect)',
        description: 'Integrate Stripe Connect (Express accounts) into our Node.js marketplace backend: onboarding, split payments, refunds, webhooks, and reconciliation reports. Strong testing culture required.',
        skills: ['Node.js', 'Stripe', 'PostgreSQL', 'API Design'], budget: 3200, category: 'Web Development',
        deadline: new Date(now + 21 * 86400000).toISOString().slice(0, 10), experienceLevel: 'Intermediate', type: 'fixed',
        freelancersRequired: 1, attachments: [], status: 'in_progress', selectedFreelancerIds: ['u-ava'], createdAt: d(14),
      },
      {
        id: 'p-content', clientId: 'u-priya', title: 'SEO blog content — 12 articles on e-commerce',
        description: 'Twelve 1,500-word articles targeting mid-funnel e-commerce keywords. Briefs and keyword research provided. Native-level English, conversational but authoritative tone.',
        skills: ['SEO', 'Copywriting', 'Content Strategy'], budget: 1800, category: 'Writing & Content',
        deadline: new Date(now + 35 * 86400000).toISOString().slice(0, 10), experienceLevel: 'Entry', type: 'fixed',
        freelancersRequired: 2, attachments: ['content-briefs.docx'], status: 'open', selectedFreelancerIds: [], createdAt: d(5),
      },
      {
        id: 'p-devops', clientId: 'u-marcus', title: 'Kubernetes migration & CI/CD overhaul',
        description: 'Migrate 6 services from EC2 to EKS with Terraform, plus GitHub Actions pipelines, secrets management, and observability (Grafana stack). Documentation is a first-class deliverable.',
        skills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD'], budget: 85, category: 'DevOps & Cloud',
        deadline: new Date(now + 50 * 86400000).toISOString().slice(0, 10), experienceLevel: 'Expert', type: 'hourly',
        freelancersRequired: 1, attachments: ['infra-diagram.png'], status: 'open', selectedFreelancerIds: [], createdAt: d(8),
      },
      {
        id: 'p-done', clientId: 'u-marcus', title: 'Marketing site redesign', 
        description: 'Redesign and rebuild of novalabs.io marketing site — completed engagement.',
        skills: ['Next.js', 'Design', 'Copywriting'], budget: 5200, category: 'Web Development',
        deadline: new Date(d(20)).toISOString().slice(0, 10), experienceLevel: 'Expert', type: 'fixed',
        freelancersRequired: 1, attachments: [], status: 'completed', selectedFreelancerIds: ['u-ava'], createdAt: d(80),
      },
    ],
    applications: [
      { id: 'a1', projectId: 'p-api', freelancerId: 'u-ava', proposal: 'I\u2019ve shipped three Stripe Connect integrations, including split payments and webhook reconciliation. I can start Monday and deliver in 3 weeks with full test coverage.', expectedBudget: 3200, estimatedTime: '3 weeks', status: 'accepted', createdAt: d(13) },
      { id: 'a2', projectId: 'p-dash', freelancerId: 'u-ava', proposal: 'Dashboards are my specialty — see Pulse Analytics in my portfolio (40+ chart components). I\u2019d build on Recharts + a custom token system matching your brand guide, delivered in 4 sprints with weekly demos.', expectedBudget: 4200, estimatedTime: '4 weeks', status: 'pending', createdAt: d(2) },
      { id: 'a3', projectId: 'p-dash', freelancerId: 'u-kai', proposal: 'Full-stack engineer, strong React + data-viz experience. I can also optimize your API payloads for chart performance while I\u2019m in there.', expectedBudget: 4500, estimatedTime: '5 weeks', status: 'pending', createdAt: d(2) },
      { id: 'a4', projectId: 'p-dash', freelancerId: 'u-leo', proposal: 'Primarily mobile but deep React experience. Happy to take this at a competitive rate to build web portfolio.', expectedBudget: 3600, estimatedTime: '6 weeks', status: 'pending', createdAt: d(1) },
      { id: 'a5', projectId: 'p-mobile', freelancerId: 'u-leo', proposal: 'Offline-first RN is exactly my lane — I built MercadoLibre\u2019s driver app sync queue. Expo + WatermelonDB is my recommended stack. Can demo a sync prototype in week one.', expectedBudget: 58, estimatedTime: '9 weeks', status: 'pending', createdAt: d(4) },
      { id: 'a6', projectId: 'p-rag', freelancerId: 'u-ira', proposal: 'I run production RAG at 1M queries/day. Proposal: hybrid retrieval (BM25 + embeddings), reranking, cited answers, and a ragas eval harness so you can measure quality objectively.', expectedBudget: 7800, estimatedTime: '5 weeks', status: 'pending', createdAt: d(1) },
    ],
    messages: [
      { id: 'm1', projectId: 'p-api', senderId: 'u-marcus', receiverId: 'u-ava', text: 'Welcome aboard, Ava! Excited to get started. I\u2019ve shared the repo access.', createdAt: d(12) },
      { id: 'm2', projectId: 'p-api', senderId: 'u-ava', receiverId: 'u-marcus', text: 'Thanks Marcus! Repo cloned. I\u2019ll have the Connect onboarding flow in review by Thursday.', createdAt: d(12) + 3600000 },
      { id: 'm3', projectId: 'p-api', senderId: 'u-ava', receiverId: 'u-marcus', text: 'Here\u2019s the webhook architecture doc for review.', fileName: 'webhook-architecture.pdf', createdAt: d(9) },
      { id: 'm4', projectId: 'p-api', senderId: 'u-marcus', receiverId: 'u-ava', text: 'This looks great — approved. One note: let\u2019s add idempotency keys on refunds.', createdAt: d(8) },
    ],
    notifications: [
      { id: 'n1', userId: 'u-ava', type: 'accepted', text: 'Marcus Reed accepted your application for “Payments API integration”', link: '/messages', read: true, createdAt: d(13) },
      { id: 'n2', userId: 'u-ava', type: 'message', text: 'New message from Marcus Reed', link: '/messages', read: false, createdAt: d(8) },
      { id: 'n3', userId: 'u-marcus', type: 'application', text: 'Ava Sinclair applied to “Analytics dashboard for SaaS platform”', link: '/client/projects/p-dash/applicants', read: false, createdAt: d(2) },
      { id: 'n4', userId: 'u-marcus', type: 'application', text: 'Kai Nakamura applied to “Analytics dashboard for SaaS platform”', link: '/client/projects/p-dash/applicants', read: false, createdAt: d(2) },
      { id: 'n5', userId: 'u-marcus', type: 'application', text: 'Leo Fernandez applied to “React Native app for field technicians”', link: '/client/projects/p-mobile/applicants', read: false, createdAt: d(4) },
    ],
    saved: [
      { userId: 'u-ava', projectId: 'p-brand' },
      { userId: 'u-ava', projectId: 'p-devops' },
    ],
  };
}
